title: Wenwen Hou's Homepage
page-top-title: Wenwen Hou
top-section-bg-text: Mechanical Engineering
home-subtitle: Wenwen Hou&ensp;|&ensp;侯文文
copyright-text: '&copy; Wenwen Hou 2023-2025. All Rights Reserved.'
